pipeline:
  frontend:
    image: plugins/docker
    repo: failender/dsa-frontend
    tags: latest
    dockerfile: frontend/Dockerfile
    context: frontend
    secrets: [ docker_username, docker_password ]
  backend:
    image: plugins/docker  
    repo: failender/dsa-backend
    tags: latest
    dockerfile: backend/Dockerfile
    context: backend
    secrets: [ docker_username, docker_password ]
  deploy:
    image: plugins/docker
    command:
        - docker service update --image failender/dsa-frontend:latest dsa --detach=false
        - docker service update --image failender/dsa-backend:latest dsa --detach=false      
    when:
      status: success